apiVersion: apps/v1
kind: Deployment
metadata:
   name: pavan-stockone-deployment
   namespace: default
spec:
   replicas: 5
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: pavan-stockone
              image: pavan/stockone:0.0.1.RELEASE
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: pavan-stockone-entrypoint
   namespace: default
spec:
   type: NodePort
   selector:
        bb: web
   ports:
      - port: 8081
        targetPort: 8081
        nodePort: 30001